inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  UseCache: true
  CacheRootDirectory: tmp/rubocop
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'test/jobs/*'
    - 'sorbet/**/*'

Naming/InclusiveLanguage:
  Enabled: false

Layout/LineLength:
  Max: 140

Naming/FileName:
  Enabled: false