dist: xenial
language: minimal

git:
  depth: 1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker build --build-arg BUNDLE_GEMFILE="$BUNDLE_GEMFILE" -t shopify/semian-ci:latest -f dockerfiles/semian-ci .
  - docker-compose -f docker-compose.ci.yml up --force-recreate -d

services:
  - docker

gemfile:
  - Gemfile
  - gemfiles/hiredis-0-6.gemfile
  - gemfiles/mysql2-0-4-10.gemfile

script:
  - docker exec -it semian ./scripts/run_tests.sh

notifications:
  email: false
