language: ruby

sudo: false

before_install:
  - wget -O toxiproxy-1.0.0.deb https://github.com/Shopify/toxiproxy/releases/download/v1.0.0/toxiproxy_1.0.0_amd64.deb
  - sudo dpkg -i toxiproxy-1.0.0.deb
  - sudo service start toxiproxy

rvm:
  - 2.1.1
