version: "3.7"
services:
  semian:
    image: shopify/semian-ci:latest
    container_name: semian
    depends_on: 
    - redis
    - mysql
    - toxiproxy
    command: sleep infinity
      
  toxiproxy:
    image: shopify/toxiproxy:latest
    container_name: toxiproxy
    depends_on: 
    - redis
    - mysql

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
